#!/usr/bin/env node
/**
 * Writes src/data/hotel-coordinates.json from Nominatim. Runs offline because the
 * usage policy forbids bulk or per-page-view querying:
 * https://operations.osmfoundation.org/policies/nominatim/
 *
 * Env: NOMINATIM_EMAIL (recommended), NOMINATIM_USER_AGENT, NOMINATIM_BASE_URL.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, "..")

const SEED_PATH = resolve(repoRoot, "src/data/mock-data.json")
const OUTPUT_PATH = resolve(repoRoot, "src/data/hotel-coordinates.json")

const BASE_URL =
  process.env.NOMINATIM_BASE_URL ?? "https://nominatim.openstreetmap.org/search"

const USER_AGENT =
  process.env.NOMINATIM_USER_AGENT ??
  "hotel-discovery-interface/0.0.1 (offline geocoding script; https://github.com/)"

// Policy maximum is 1 request/second; leave headroom.
const REQUEST_INTERVAL_MS = 1100

const force = process.argv.includes("--force")

const sleep = (ms) => new Promise((done) => setTimeout(done, ms))

/** `null` means no match, so callers fall back; HTTP failures throw and stop the run. */
async function query(params) {
  const url = new URL(BASE_URL)
  url.searchParams.set("format", "jsonv2")
  url.searchParams.set("limit", "1")

  for (const [key, value] of Object.entries(params)) {
    if (value) {
      url.searchParams.set(key, value)
    }
  }

  if (process.env.NOMINATIM_EMAIL) {
    url.searchParams.set("email", process.env.NOMINATIM_EMAIL)
  }

  const response = await fetch(url, {
    headers: { "User-Agent": USER_AGENT, "Accept-Language": "en" },
  })

  if (!response.ok) {
    throw new Error(`Nominatim responded ${response.status} for ${url.search}`)
  }

  const results = await response.json()
  const [match] = Array.isArray(results) ? results : []

  if (!match) {
    return null
  }

  return {
    lat: Number.parseFloat(match.lat),
    lng: Number.parseFloat(match.lon),
    displayName: match.display_name ?? "",
  }
}

/** Most specific first. The seed's fictional streets fall through to the city; real ones won't. */
async function geocodeHotel(hotel) {
  const { street, city, state, zip_code: postalcode, country } = hotel.address

  const attempts = [
    {
      precision: "address",
      params: { street, city, state, postalcode, country },
    },
    {
      precision: "address",
      params: { q: [street, city, state, postalcode, country].join(", ") },
    },
    { precision: "city", params: { city, state, country } },
    { precision: "city", params: { q: [city, country].join(", ") } },
  ]

  for (const [index, attempt] of attempts.entries()) {
    if (index > 0) {
      await sleep(REQUEST_INTERVAL_MS)
    }

    const match = await query(attempt.params)

    if (match) {
      return { ...match, precision: attempt.precision }
    }
  }

  return null
}

async function main() {
  const seed = JSON.parse(await readFile(SEED_PATH, "utf8"))

  let existing = { hotels: {} }
  if (!force) {
    try {
      existing = JSON.parse(await readFile(OUTPUT_PATH, "utf8"))
    } catch {
      // No cache yet — start from scratch.
    }
  }

  const resolved = { ...(existing.hotels ?? {}) }
  const pending = seed.filter((hotel) => !resolved[hotel.id])

  if (pending.length === 0) {
    console.log(
      `Nothing to do — all ${seed.length} hotels are cached. Use --force to refresh.`
    )
    return
  }

  console.log(
    `Geocoding ${pending.length} of ${seed.length} hotels via Nominatim ` +
      `(~${Math.ceil((pending.length * REQUEST_INTERVAL_MS) / 1000)}s at the ` +
      `policy rate limit)…`
  )

  let failures = 0

  for (const [index, hotel] of pending.entries()) {
    if (index > 0) {
      await sleep(REQUEST_INTERVAL_MS)
    }

    const match = await geocodeHotel(hotel)

    if (!match) {
      failures += 1
      console.warn(`  ✗ ${hotel.id}  ${hotel.name} — no match`)
      continue
    }

    resolved[hotel.id] = match
    console.log(
      `  ✓ ${hotel.id}  ${hotel.name} → ${match.lat}, ${match.lng} ` +
        `(${match.precision})`
    )
  }

  const byPrecision = Object.values(resolved).reduce((counts, entry) => {
    counts[entry.precision] = (counts[entry.precision] ?? 0) + 1
    return counts
  }, {})

  const output = {
    _meta: {
      source: "OpenStreetMap Nominatim — https://nominatim.openstreetmap.org",
      license: "Geocoding data © OpenStreetMap contributors, ODbL 1.0",
      generatedAt: new Date().toISOString().slice(0, 10),
      note: "Generated by `npm run geocode`. Do not query Nominatim at request time.",
    },
    hotels: Object.fromEntries(
      Object.entries(resolved).sort(([a], [b]) => a.localeCompare(b))
    ),
  }

  await mkdir(dirname(OUTPUT_PATH), { recursive: true })
  await writeFile(OUTPUT_PATH, `${JSON.stringify(output, null, 2)}\n`, "utf8")

  console.log(
    `\nWrote ${Object.keys(resolved).length} coordinates to ` +
      `src/data/hotel-coordinates.json ` +
      `(${Object.entries(byPrecision)
        .map(([precision, count]) => `${count} ${precision}`)
        .join(", ")}${failures > 0 ? `, ${failures} unresolved` : ""}).`
  )
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
